# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b042b38e06b8327c2243d3d988ff5d8e93c3fa3da4fe581c63b787c69502ade60c9944e4111b1218865e60d5230d2f925c1ab5df0e3d4527039e8bc1e07c95c7

test:
  secret_key_base: 4fa82d40a67a421ed7a32b5473b2949a90cd2186b2105d5d424897569c53edfcc65602452db05016daa7657e6ad3df1c3bc4daad577418987ab4d1f38bf0f55f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: cd9d324ae7be966cc844310997081066f775a97f317c23267fbfbbaff5cbf878e280f4abeeb031811f7993d9e60fbda0448d5bfc6c54f4d533845f9cbb887da7
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
